import time
import numpy as np
from collections import defaultdict
import pickle
import numpy as np
import pandas as pd



num_flows = 0
num_benign = 0
num_malicious = 0

def load_model(path):
    with open(path, 'rb') as f:
        model = pickle.load(f)
    return model

def predict(features):
    global num_benign, num_malicious, num_flows
    # features = np.array([list(features.values())])
    features = pd.DataFrame([features])
    prediction = ids_model.predict(features)
    if(np.argmax(prediction) == 0):
        print("--- Normal Traffic Detected ---")
        num_benign = num_benign + 1
    else:
        print("--- Malicious Traffic Detected ---")
        num_malicious = num_malicious + 1
    num_flows = num_flows + 1
    #if num_flows % 10 == 0:
        #print(f"\nTotal Flows Processed: {num_flows}, Benign: {num_benign}, Malicious: {num_malicious}\n")

ids_model = load_model('models/rf_ids_model.pkl')

#Partially generated by GPT-5
class Flow:
    def __init__(self, key):
        self.key = key  # (src, dst, sport, dport, proto)

        # Timing
        self.start_time = None
        self.last_seen = None

        # Directional packet counters
        self.fwd_pkts = 0
        self.bwd_pkts = 0
        self.fwd_bytes = 0
        self.bwd_bytes = 0

        # Packet sizes
        self.pkt_sizes = []

        # Inter-arrival times
        self.fwd_iat = []
        self.bwd_iat = []
        self.last_fwd_time = None
        self.last_bwd_time = None

        # TCP flags
        self.syn = 0
        self.fin = 0
        self.rst = 0
        self.ack = 0
        self.psh = 0
        self.urg = 0
        self.ece = 0
        self.cwe = 0

        # Window sizes
        self.fwd_init_win = None
        self.bwd_init_win = None

        # Subflow statistics
        self.subflow_fwd_pkts = 0
        self.subflow_bwd_pkts = 0
        self.subflow_fwd_bytes = 0
        self.subflow_bwd_bytes = 0


from scapy.layers.inet import IP, TCP, UDP

def update_flow(flow, pkt):
    now = pkt.time

    # Set flow start
    if flow.start_time is None:
        flow.start_time = now
        flow.last_seen = now

    size = len(pkt)
    flow.pkt_sizes.append(size)

    # Determine direction
    src, dst, sport, dport, proto = flow.key

    if IP in pkt:
        if pkt[IP].src == src and pkt[IP].dst == dst:
            direction = "fwd"
        else:
            direction = "bwd"
    else:
        return

    # Update counters
    if direction == "fwd":
        flow.fwd_pkts += 1
        flow.fwd_bytes += size

        if flow.last_fwd_time:
            flow.fwd_iat.append(now - flow.last_fwd_time)
        flow.last_fwd_time = now
    else:
        flow.bwd_pkts += 1
        flow.bwd_bytes += size

        if flow.last_bwd_time:
            flow.bwd_iat.append(now - flow.last_bwd_time)
        flow.last_bwd_time = now

    # TCP flags
    if TCP in pkt:
        flags = pkt[TCP].flags
        flow.syn += int(flags & 0x02 != 0)
        flow.fin += int(flags & 0x01 != 0)
        flow.rst += int(flags & 0x04 != 0)
        flow.ack += int(flags & 0x10 != 0)
        flow.psh += int(flags & 0x08 != 0)
        flow.urg += int(flags & 0x20 != 0)
        flow.ece += int(flags & 0x40 != 0)
        flow.cwe += int(flags & 0x80 != 0)

        # Initial window
        if direction == "fwd" and flow.fwd_init_win is None:
            flow.fwd_init_win = pkt[TCP].window
        if direction == "bwd" and flow.bwd_init_win is None:
            flow.bwd_init_win = pkt[TCP].window

    flow.last_seen = now

def safe_stats(arr):
    if len(arr) == 0:
        return (0, 0, 0, 0, 0)
    return (len(arr), np.mean(arr), np.std(arr), np.min(arr), np.max(arr))

def extract_features(flow):
    print('Analyzing flow: {}:{} -> {}:{} Proto: {}'.format(flow.key[0], flow.key[2], flow.key[1], flow.key[3], flow.key[4]))
    dur = flow.last_seen - flow.start_time if flow.start_time else 0

    # Packet size stats
    pkt_tot, pkt_mean, pkt_std, pkt_min, pkt_max = safe_stats(flow.pkt_sizes)

    # IAT stats
    f_iat_tot, f_iat_mean, f_iat_std, f_iat_min, f_iat_max = safe_stats(flow.fwd_iat)
    b_iat_tot, b_iat_mean, b_iat_std, b_iat_min, b_iat_max = safe_stats(flow.bwd_iat)

    total_pkts = flow.fwd_pkts + flow.bwd_pkts
    total_bytes = flow.fwd_bytes + flow.bwd_bytes

    features = {
        "Flow Duration": dur,
        "Tot Fwd Pkts": flow.fwd_pkts,
        "Tot Bwd Pkts": flow.bwd_pkts,

        "TotLen Fwd Pkts": flow.fwd_bytes,
        "TotLen Bwd Pkts": flow.bwd_bytes,
        
        "Fwd Pkt Len Max": f_iat_max,
        "Fwd Pkt Len Min": f_iat_min,
        "Fwd Pkt Len Mean": (flow.fwd_bytes / flow.fwd_pkts) if flow.fwd_pkts else 0,
        "Fwd Pkt Len Std": f_iat_std,
        
        "Bwd Pkt Len Max": b_iat_max,
        "Bwd Pkt Len Min": b_iat_min,
        "Bwd Pkt Len Mean": (flow.bwd_bytes / flow.bwd_pkts) if flow.bwd_pkts else 0,
        "Bwd Pkt Len Std": b_iat_std,

        "Flow Byts/s": (total_bytes / dur) if dur > 0 else 0,
        "Flow Pkts/s": (total_pkts / dur) if dur > 0 else 0,

        # IAT stats
        "Fwd IAT Tot" : f_iat_tot,
        "Fwd IAT Mean": f_iat_mean,
        "Fwd IAT Std": f_iat_std,
        "Fwd IAT Max": f_iat_max,
        "Fwd IAT Min": f_iat_min,
        "Bwd IAT Tot" : b_iat_tot,
        "Bwd IAT Mean": b_iat_mean,
        "Bwd IAT Std": b_iat_std,
        "Bwd IAT Max": b_iat_max,
        "Bwd IAT Min": b_iat_min,

        # Packet length stats
        "Pkt Len Min": pkt_min,
        "Pkt Len Max": pkt_max,
        "Pkt Len Mean": pkt_mean,
        "Pkt Len Std": pkt_std,
        
        # TCP flags
        "FIN Flag Cnt": flow.fin,
        "SYN Flag Cnt": flow.syn,
        "RST Flag Cnt": flow.rst,
        "PSH Flag Cnt": flow.psh,
        "ACK Flag Cnt": flow.ack,
        "URG Flag Cnt": flow.urg,
        "CWE Flag Count": flow.cwe,
        "ECE Flag Cnt": flow.ece,

        # Subflows
        "Subflow Fwd Pkts": flow.fwd_pkts,
        "Subflow Fwd Byts": flow.fwd_bytes,
        "Subflow Bwd Pkts": flow.bwd_pkts,
        "Subflow Bwd Byts": flow.bwd_bytes,

        # Initial windows
        "Init Fwd Win Byts": flow.fwd_init_win or 0,
        "Init Bwd Win Byts": flow.bwd_init_win or 0,
    }

    return features

def expire_flows(flow_table, timeout=60):
    finished = []
    now = time.time()

    for key, flow in list(flow_table.items()):
        if now - flow.last_seen > timeout:
            finished.append((key, flow))
            del flow_table[key]

    return finished

from scapy.all import sniff

def get_flow_key(pkt):
    if IP not in pkt:
        return None
    ip = pkt[IP]
    proto = ip.proto

    # TCP
    if proto == 6 and TCP in pkt:
        sport = pkt[TCP].sport
        dport = pkt[TCP].dport

    # UDP
    elif proto == 17 and UDP in pkt:
        sport = pkt[UDP].sport
        dport = pkt[UDP].dport

    else:
        return None

    #print('Analyzing flow: {}:{} -> {}:{} Proto: {}'.format(ip.src, sport, ip.dst, dport, proto))
    # return 5-tuple key
    return (ip.src, ip.dst, sport, dport, proto)

flows = defaultdict(lambda: None)

def handler(pkt):

    # print('here')
    key = get_flow_key(pkt)
    if not key:
        return
    
    if flows[key] is None:
        flows[key] = Flow(key)
    
    update_flow(flows[key], pkt)

    for k, f in expire_flows(flows):
        features = extract_features(f)
        predict(features)
        #print(features)

def target():
    sniff(iface="Realtek RTL8852BE WiFi 6 802.11ax PCIe Adapter", store=False, prn=handler)

if __name__ == '__main__':
    #ids_model = load_model('models/rf_ids_model.pkl')
    sniff(iface="Realtek RTL8852BE WiFi 6 802.11ax PCIe Adapter", store=False, prn=handler)

    print("\n--- Statistics ---")
    print(f"Total Flows Processed: {num_flows}")
    print(f"Benign Flows: {num_benign}")
    print(f"Malicious Flows: {num_malicious}")
    print("------------------")
